name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render service like browser
        run: |
          echo "🔹 Trigger Time: $(date '+%Y-%m-%d %H:%M:%S %Z')"

          URL="https://naukri-profile-updator.onrender.com/naukari/stats"
          echo "Pinging: $URL"

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.5" \
            -H "Connection: keep-alive" \
            --max-time 60 \
            $URL
          )

          echo "HTTP Response: $RESPONSE"

          if [ "$RESPONSE" -eq 200 ]; then
            echo "✅ Render service is UP"
          else
            echo "⚠️ Render service responded with HTTP $RESPONSE (might be down or sleeping)"
          fi
